- filename: pdfs.bib
  search_type: LOCAL_PAPER_INDEX
  source_name: ICIS
  source_url: /home/gerit/ownCloud/data/journals/ICIS
  outlet: conference=International Conference on Information Systems
  sub_dir_pattern: year
  search_parameters: NA
  comment: NA
