- filename: DBLP.bib
  search_type: FEED
  source_name: International Confereence on Information Systems
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: SCOPE venue_key='conf/icis' AND journal_abbreviated='icis'
  last_sync: null
  comment: ''
  outlet: null
  sub_dir_pattern: null
  search_endpoint: dblp
- filename: pdfs.bib
  search_type: FEED
  source_name: ICIS
  source_url: pdfs
  search_parameters:
  - endpoint: pdfs_directory
    params: SCOPE path='pdfs' WITH conference='International Conference on Information Systems' AND sub_dir_pattern='year'
  comment: NA
